// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrendyolClone.Data;

#nullable disable

namespace TrendyolClone.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TrendyolClone.Models.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresSatiri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostaKodu")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Varsayilan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Adresler");
                });

            modelBuilder.Entity("TrendyolClone.Models.AramaGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AramaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("AramaTerimi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAdresi")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SonucSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("AramaGecmisleri");
                });

            modelBuilder.Entity("TrendyolClone.Models.AramaTiklama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AramaGecmisiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TiklamaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AramaGecmisiId");

                    b.HasIndex("UrunId");

                    b.ToTable("AramaTiklamalari");
                });

            modelBuilder.Entity("TrendyolClone.Models.Bildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GonderimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("HataMesaji")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parametreler")
                        .HasColumnType("TEXT");

                    b.Property<string>("SablonKodu")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonNo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Turu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.HasIndex("OlusturmaTarihi");

                    b.HasIndex("KullaniciId", "OlusturmaTarihi");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("TrendyolClone.Models.BildirimSablonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Turu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("BildirimSablonlari");
                });

            modelBuilder.Entity("TrendyolClone.Models.BildirimTercihi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmailBildirimleri")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IadeBildirimleri")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KampanyaBildirimleri")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SiparisBildirimleri")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmsBildirimleri")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UrunBildirimleri")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.ToTable("BildirimTercihleri");
                });

            modelBuilder.Entity("TrendyolClone.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AraToplam")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EFaturaMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EFaturaUuid")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FaturaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaUnvani")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IndirimTutari")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KDV")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KargoUcreti")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SiparisId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Toplam")
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiNo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("TrendyolClone.Models.Favori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.HasIndex("KullaniciId", "UrunId")
                        .IsUnique();

                    b.ToTable("Favoriler");
                });

            modelBuilder.Entity("TrendyolClone.Models.Iade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IadeKargoTakipNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IadeKargoTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IadeTutari")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Neden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OdemeYapildiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedNedeni")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SiparisId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SiparisId");

                    b.ToTable("Iadeler");
                });

            modelBuilder.Entity("TrendyolClone.Models.IadeUrunu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("TEXT");

                    b.Property<int>("IadeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IadeId");

                    b.HasIndex("UrunId");

                    b.ToTable("IadeUrunleri");
                });

            modelBuilder.Entity("TrendyolClone.Models.IslemKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EskiDeger")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAdresi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Islem")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAjanı")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VarlikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VarlikTipi")
                        .HasColumnType("TEXT");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YoneticiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IslemKayitlari");
                });

            modelBuilder.Entity("TrendyolClone.Models.Kampanya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IndirimMiktari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KullanimSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaksimumIndirim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinimumSepetTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinimumUrunAdedi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Oncelik")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamIndirimTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Turu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Kampanyalar", (string)null);
                });

            modelBuilder.Entity("TrendyolClone.Models.KargoFirma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiSecret")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DesiBasinaUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KgBasinaUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TemelUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UcretsizKargoLimiti")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("KargoFirmalari", (string)null);
                });

            modelBuilder.Entity("TrendyolClone.Models.KargoHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("KargoTakipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lokasyon")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KargoTakipId");

                    b.ToTable("KargoHareketler");
                });

            modelBuilder.Entity("TrendyolClone.Models.KargoOlculeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Agirlik")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Boy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("En")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("KargoUcreti")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UcretsizKargo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Yukseklik")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UrunId")
                        .IsUnique();

                    b.ToTable("KargoOlculeri");
                });

            modelBuilder.Entity("TrendyolClone.Models.KargoTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KargoDurumu")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KargoFirmasi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiparisId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TahminiTeslimatTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TakipNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("KargoTakipler");
                });

            modelBuilder.Entity("TrendyolClone.Models.KargoUcret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CikisIli")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KargoFirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TahminiGun")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VarisIli")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KargoFirmaId", "CikisIli", "VarisIli");

                    b.ToTable("KargoUcretleri", (string)null);
                });

            modelBuilder.Entity("TrendyolClone.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("TrendyolClone.Models.KayitliSepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KayitliSepetler", (string)null);
                });

            modelBuilder.Entity("TrendyolClone.Models.KayitliSepetUrunu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KayitliSepetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VaryasyonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KayitliSepetId");

                    b.HasIndex("UrunId");

                    b.HasIndex("VaryasyonId");

                    b.ToTable("KayitliSepetUrunleri", (string)null);
                });

            modelBuilder.Entity("TrendyolClone.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilFotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonNumarasi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("TrendyolClone.Models.Kupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IndirimMiktari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IndirimTuru")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KullaniciBasinaKullanimSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullanimSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaksimumIndirim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaksimumKullanimSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MinimumSepetTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Kuponlar", (string)null);
                });

            modelBuilder.Entity("TrendyolClone.Models.KuponKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KuponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KuponId");

                    b.ToTable("KuponKategoriler", (string)null);
                });

            modelBuilder.Entity("TrendyolClone.Models.KuponKullanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IndirimTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IpAdresi")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KullanimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KuponId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SepetTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SiparisId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("KuponId");

                    b.HasIndex("SiparisId");

                    b.ToTable("KuponKullanimlari", (string)null);
                });

            modelBuilder.Entity("TrendyolClone.Models.Marka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunSayisi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Markalar", (string)null);
                });

            modelBuilder.Entity("TrendyolClone.Models.OdemeIslemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .HasColumnType("TEXT");

                    b.Property<string>("HataKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("HataMesaji")
                        .HasColumnType("TEXT");

                    b.Property<string>("IslemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("KartSonDortHane")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdemeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdemeYontemi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiparisId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("OdemeIslemleri");
                });

            modelBuilder.Entity("TrendyolClone.Models.OdemeYontemiAyari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankaAdi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EkBilgi")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HesapSahibi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IbanNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OdemeYontemleri");
                });

            modelBuilder.Entity("TrendyolClone.Models.PopulerArama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AramaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AramaTerimi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("AylikAramaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("GunlukAramaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HaftalikAramaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SonAramaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("PopulerAramalar");
                });

            modelBuilder.Entity("TrendyolClone.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("TrendyolClone.Models.SepetUrunu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.HasIndex("KullaniciId", "UrunId")
                        .IsUnique();

                    b.ToTable("SepetUrunleri");
                });

            modelBuilder.Entity("TrendyolClone.Models.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNotu")
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FaturaAdresi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IndirimTutari")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KargoUcreti")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdemeYontemi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiparisNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeslimatAdresi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("TrendyolClone.Models.SiparisDurumGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DegistirenKisi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiparisId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SiparisId");

                    b.ToTable("SiparisDurumGecmisleri");
                });

            modelBuilder.Entity("TrendyolClone.Models.SiparisKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiparisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.HasIndex("UrunId");

                    b.ToTable("SiparisKalemleri");
                });

            modelBuilder.Entity("TrendyolClone.Models.SiteAyarlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltBilgiMetni")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("IletisimEmail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IletisimTelefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoIcon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteAciklamasi")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteAyarlari");
                });

            modelBuilder.Entity("TrendyolClone.Models.Tedarikci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiAnahtari")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiGizliAnahtari")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IletisimEmail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IletisimTelefon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KomisyonOrani")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeslimatGunu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tedarikciler");
                });

            modelBuilder.Entity("TrendyolClone.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("FavoriSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("GoruntulenmeSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("IndirimliFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarkaAdi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MarkaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PopuleriteSkor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Puan")
                        .HasColumnType("REAL");

                    b.Property<string>("ResimUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SatinAlmaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TedarikciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TedarikciUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TedarikciUrunId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("YorumSayisi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("MarkaId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TedarikciId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunCevap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cevap")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Resmi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoruId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YoneticiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SoruId");

                    b.HasIndex("YoneticiId");

                    b.ToTable("UrunCevaplari");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunKampanya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KampanyaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullanilanStok")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OzelIndirimMiktari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StokLimiti")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KampanyaId");

                    b.HasIndex("UrunId", "KampanyaId")
                        .IsUnique();

                    b.ToTable("UrunKampanyalari", (string)null);
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunOzellik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("OzellikAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OzellikDegeri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("UrunOzellikleri");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunResim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnaResim")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResimUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VaryasyonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.HasIndex("VaryasyonId");

                    b.ToTable("UrunResimleri");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunSoru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cevaplandi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soru")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("UrunSorulari");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunVaryasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnaResim")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Beden")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DigerOzellik")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IndirimliFiyat")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinStok")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renk")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("UrunId");

                    b.ToTable("UrunVaryasyonlari");
                });

            modelBuilder.Entity("TrendyolClone.Models.Yonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Yoneticiler");
                });

            modelBuilder.Entity("TrendyolClone.Models.Yorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DogrulanmisSatin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Onaylandi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("TrendyolClone.Models.Adres", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("TrendyolClone.Models.AramaGecmisi", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId");

                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Kategori");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("TrendyolClone.Models.AramaTiklama", b =>
                {
                    b.HasOne("TrendyolClone.Models.AramaGecmisi", "AramaGecmisi")
                        .WithMany("Tiklamalar")
                        .HasForeignKey("AramaGecmisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AramaGecmisi");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TrendyolClone.Models.Bildirim", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("TrendyolClone.Models.BildirimTercihi", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("TrendyolClone.Models.Fatura", b =>
                {
                    b.HasOne("TrendyolClone.Models.Siparis", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("TrendyolClone.Models.Favori", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TrendyolClone.Models.Iade", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Siparis", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("TrendyolClone.Models.IadeUrunu", b =>
                {
                    b.HasOne("TrendyolClone.Models.Iade", "Iade")
                        .WithMany("Urunler")
                        .HasForeignKey("IadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iade");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TrendyolClone.Models.KargoHareket", b =>
                {
                    b.HasOne("TrendyolClone.Models.KargoTakip", "KargoTakip")
                        .WithMany("Hareketler")
                        .HasForeignKey("KargoTakipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KargoTakip");
                });

            modelBuilder.Entity("TrendyolClone.Models.KargoOlculeri", b =>
                {
                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithOne()
                        .HasForeignKey("TrendyolClone.Models.KargoOlculeri", "UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TrendyolClone.Models.KargoTakip", b =>
                {
                    b.HasOne("TrendyolClone.Models.Siparis", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("TrendyolClone.Models.KargoUcret", b =>
                {
                    b.HasOne("TrendyolClone.Models.KargoFirma", "KargoFirma")
                        .WithMany("Ucretler")
                        .HasForeignKey("KargoFirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KargoFirma");
                });

            modelBuilder.Entity("TrendyolClone.Models.KayitliSepet", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("TrendyolClone.Models.KayitliSepetUrunu", b =>
                {
                    b.HasOne("TrendyolClone.Models.KayitliSepet", "KayitliSepet")
                        .WithMany("Urunler")
                        .HasForeignKey("KayitliSepetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.UrunVaryasyon", "Varyasyon")
                        .WithMany()
                        .HasForeignKey("VaryasyonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KayitliSepet");

                    b.Navigation("Urun");

                    b.Navigation("Varyasyon");
                });

            modelBuilder.Entity("TrendyolClone.Models.Kullanici", b =>
                {
                    b.HasOne("TrendyolClone.Models.Rol", "Rol")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("TrendyolClone.Models.KuponKategori", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Kupon", "Kupon")
                        .WithMany("GecerliKategoriler")
                        .HasForeignKey("KuponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Kupon");
                });

            modelBuilder.Entity("TrendyolClone.Models.KuponKullanimi", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Kupon", "Kupon")
                        .WithMany("Kullanimlar")
                        .HasForeignKey("KuponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Siparis", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kullanici");

                    b.Navigation("Kupon");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("TrendyolClone.Models.OdemeIslemi", b =>
                {
                    b.HasOne("TrendyolClone.Models.Siparis", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("TrendyolClone.Models.PopulerArama", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("TrendyolClone.Models.SepetUrunu", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TrendyolClone.Models.Siparis", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany("Siparisler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("TrendyolClone.Models.SiparisDurumGecmisi", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.HasOne("TrendyolClone.Models.Siparis", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("TrendyolClone.Models.SiparisKalemi", b =>
                {
                    b.HasOne("TrendyolClone.Models.Siparis", "Siparis")
                        .WithMany("SiparisKalemleri")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TrendyolClone.Models.Urun", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Marka", "Marka")
                        .WithMany("Urunler")
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrendyolClone.Models.Tedarikci", "Tedarikci")
                        .WithMany("Urunler")
                        .HasForeignKey("TedarikciId");

                    b.Navigation("Kategori");

                    b.Navigation("Marka");

                    b.Navigation("Tedarikci");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunCevap", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.HasOne("TrendyolClone.Models.UrunSoru", "Soru")
                        .WithMany("Cevaplar")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Yonetici", "Yonetici")
                        .WithMany()
                        .HasForeignKey("YoneticiId");

                    b.Navigation("Kullanici");

                    b.Navigation("Soru");

                    b.Navigation("Yonetici");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunKampanya", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kampanya", "Kampanya")
                        .WithMany("UrunKampanyalari")
                        .HasForeignKey("KampanyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany("Kampanyalar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kampanya");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunOzellik", b =>
                {
                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunResim", b =>
                {
                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.UrunVaryasyon", "Varyasyon")
                        .WithMany("Resimler")
                        .HasForeignKey("VaryasyonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Urun");

                    b.Navigation("Varyasyon");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunSoru", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunVaryasyon", b =>
                {
                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TrendyolClone.Models.Yorum", b =>
                {
                    b.HasOne("TrendyolClone.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrendyolClone.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TrendyolClone.Models.AramaGecmisi", b =>
                {
                    b.Navigation("Tiklamalar");
                });

            modelBuilder.Entity("TrendyolClone.Models.Iade", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("TrendyolClone.Models.Kampanya", b =>
                {
                    b.Navigation("UrunKampanyalari");
                });

            modelBuilder.Entity("TrendyolClone.Models.KargoFirma", b =>
                {
                    b.Navigation("Ucretler");
                });

            modelBuilder.Entity("TrendyolClone.Models.KargoTakip", b =>
                {
                    b.Navigation("Hareketler");
                });

            modelBuilder.Entity("TrendyolClone.Models.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("TrendyolClone.Models.KayitliSepet", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("TrendyolClone.Models.Kullanici", b =>
                {
                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("TrendyolClone.Models.Kupon", b =>
                {
                    b.Navigation("GecerliKategoriler");

                    b.Navigation("Kullanimlar");
                });

            modelBuilder.Entity("TrendyolClone.Models.Marka", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("TrendyolClone.Models.Rol", b =>
                {
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("TrendyolClone.Models.Siparis", b =>
                {
                    b.Navigation("SiparisKalemleri");
                });

            modelBuilder.Entity("TrendyolClone.Models.Tedarikci", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("TrendyolClone.Models.Urun", b =>
                {
                    b.Navigation("Kampanyalar");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunSoru", b =>
                {
                    b.Navigation("Cevaplar");
                });

            modelBuilder.Entity("TrendyolClone.Models.UrunVaryasyon", b =>
                {
                    b.Navigation("Resimler");
                });
#pragma warning restore 612, 618
        }
    }
}
